### ISSUE TITLE
typo in tutorial page

### ISSUE THREAD

**Issue by mibillen** [GenericMappingTools/pygmt#1010]
I found a typo on the top of a tutorial page that might lead to unnecessary confusion. The error is on this page: https://www.pygmt.org/latest/tutorials/first-figure.html.  In the note about how to show a figure using the default PDF viewer there is a a set of quotes missing in the text in red: fig.show(method="external). This should be fig.show(method="external")

**Comment by seisman** [comment]
@mibillen Thanks for pointing out the typos in the documentation. The typos have been fixed in #953. 

Unfortunately, we can't make changes to the released documentation. Instead, you can view our dev documentation at https://www.pygmt.org/dev.

FYI, we're going to make a patch release v0.3.1 next week. After v0.3.1 release, the "latest" documentation will be correct.
