### ISSUE TITLE
Bump sphinx rtd theme to fix search indexing

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1149]
**Description of the problem**

The search functionality for the PyGMT docs does not work for v0.3.0 onwards. I have locally confirmed that the search functionality works on the dev docs if sphinx_rtd_theme=0.4.3 is bumped up to 0.5.1 (the latest release).

**Comment by meghanrjones** [comment]
Do we need to backport #1150, https://github.com/GenericMappingTools/pygmt/pull/1183, https://github.com/GenericMappingTools/pygmt/pull/1174, and https://github.com/GenericMappingTools/pygmt/pull/1197 or just wait for the next release? To be honest, I do not know the process for backporting to gh-pages. 

*Backporting suggestion originally posted by @weiji14 in https://github.com/GenericMappingTools/pygmt/pull/1150#pullrequestreview-624830689*

**Comment by seisman** [comment]
To do the backport, you need to checkout the v0.3.1 tag and create a new working branch, cherry-pick the related commits into that branch, build the documentation, and manually replace the old v0.3.1 documentation with the new one.

I'm not sure if it works as expected, because the documentation may have a wrong version like v0.3.1.dev1+gxxxxx, not v0.3.1.

BTW, I'm OK with waiting for the next release, rather than patching released versions.

**Comment by meghanrjones** [comment]
> To do the backport, you need to checkout the v0.3.1 tag and create a new working branch, cherry-pick the related commits into that branch, build the documentation, and manually replace the old v0.3.1 documentation with the new one.
> 
> I'm not sure if it works as expected, because the documentation may have a wrong version like v0.3.1.dev1+gxxxxx, not v0.3.1.
> 
> BTW, I'm OK with waiting for the next release, rather than patching released versions.

OK, I prefer to wait.
