### ISSUE TITLE
Redesign the tutorial section on the documentation sidebar

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1191]
We already have a long list of tutorials in the "User Guide" part. I expect more tutorials will be added in the future, and the length of the sidebar will increase. I think we need to think about how to reorganize the learning material and how to shorten the sidebar.

![image](https://user-images.githubusercontent.com/3974108/113805106-e23e7a80-972d-11eb-9801-cc9a36f9d470.png)

**Comment by michaelgrund** [comment]
Is it possible to add some folding here? E.g. unfold the individual tutorials only after clicking on "User Guide".

**Comment by weiji14** [comment]
> Is it possible to add some folding here? E.g. unfold the individual tutorials only after clicking on "User Guide".

Agree with having some folding, but how should we organize it? Beginner/Intermediate/Advanced? Or something more semantic like Basemaps/Plotting items/Grids?

Xref `geopandas` which did a restructure last year (see https://github.com/geopandas/geopandas/issues/1505), perhaps we could get some inspiration from.

**Comment by meghanrjones** [comment]
I agree with the folding ideas and like the semantic naming of sub-sections.

I would actually prefer that the section in its entirety be called 'tutorials' rather than 'user guide' because that seems more descriptive and aligns with how that section of the documentation is typically referred to in conversation.

**Comment by core-man** [comment]
> > Is it possible to add some folding here? E.g. unfold the individual tutorials only after clicking on "User Guide".
> 
> Agree with having some folding, but how should we organize it? Beginner/Intermediate/Advanced? Or something more semantic like Basemaps/Plotting items/Grids?

Yes, I'm also wondering if we could have two kinds of tutorials: **Beginner** and **Advanced**. The **Beginner** could be included in **Get Started** section and is named as `PyGMT 101` or something else, while the original **User Guide** section is renamed to be **Advanced**. See a quick example below to check how it may look like. In this example, the `projection` is an individual subsection since I think it covers too much, while the `Basics` subsection contains a few advanced tutorials.

<img width="315" alt="pygmt" src="https://user-images.githubusercontent.com/50591376/114269471-dc041300-9a39-11eb-85f7-de5bf5f9e10a.png">

Then we may think that which tutorials should be included in `PyGMT 101` and which in `Advanced/Basics`. From my point of view, the following tutorials could be within `PyGMT 101` because it seems they are often used in the usual plotting.

- Frames, ticks, titles, and labels
- Coastlines and borders
- Plotting data points
- Plot lines
- Plotting text
- Plotting Earth relief
- Adding an inset to the figure
- Making subplots
