### ISSUE TITLE
Move parts of the contributing guides to the website

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1205]
In PR #1185, we moved the maintainer's guides to the documentation (the `doc` directory), since the guides are too long and are much easier to read on the documentation website (using the sidebar links).

Similarly, the [contributing guides](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md) is also too long, with more than 500 lines now, and still increasing (#1119, #1113).

I don't think it's a good idea to move the whole CONTRIBUTING.md file to the documentation. Instead, I think we can only keep basic guides in the repository, but move advanced guides to the documentation. 

Basic guides are mainly for first-time contributors or people who are not familiar with github workflows (it means people like me will never read it). IMHO, basic guides can include sections like:

- What Can I Do?
- How Can I Talk to You?
- Reporting a Bug
- Code Review process
- General guidelines

Other sections like rules/styles of our documentation and code, instructions to run tests and generate baseline images, are too technical and can be grouped as advanced guides (even people like me need to read it sometimes).

This is just a quick idea, and I'm not sure if it would cause more confusion, but I'd like to hear your thoughts.

**Comment by core-man** [comment]
I feel we could move all of them to the documentation instead of putting them in two places. We could re-group the guides into basic and advanced ones as your suggestion. In this way, experienced contributors could still quickly find what they need, while new contributors can also know all the things in one place.

**Comment by meghanrjones** [comment]
I like scikit-learn's stucture, which has a minimal [CONTRIBUTING.md](https://github.com/scikit-learn/scikit-learn/blob/main/CONTRIBUTING.md) that primarily provides links to the contributing guides on their website. I prefer to keep some sort of CONTRIBUTING.md because people interested in contributing could do a quick search for it and I would not want to risk losing any potential contributors due to its absence.

**Comment by seisman** [comment]
Yes, I agree we should at least have a minimal CONTRIBUTING.md file.

**Comment by core-man** [comment]
If we want a minimal CONTRIBUTING.md, how about the following TOC of `CONTRIBUTING.md`:

- Contributing Guidelines
- Ground Rules
- Quick Links (some links to the planned contributing guides on the website, e.g., **What Can I Do?**, **How Can I Talk to You?**, **Reporting a Bug**)

Meanwhile, we could move all the sections to the website.

**Comment by meghanrjones** [comment]
I will open a PR based on the conversation here, because if possible it would be nice to get this in for v0.4.0 in advance of the July/August sprint/workshop.
