### ISSUE TITLE
Adding a PyGMT team page

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/pygmt#1212]
Background information:

1. It could be helpful for new contributors to know who the PyGMT maintainers are, now that the list of maintainers is growing.
2. I am working on improving the authorship guidelines and acknowledgements structure for GMT (see https://github.com/GenericMappingTools/gmt/issues/2330 for context) and envision one of the products being similar to the [Numpy team gallery](https://numpy.org/gallery/team.html), which could be hosted at www.generic-mapping-tools.org with a link from the [about page](https://www.generic-mapping-tools.org/about/). PyGMT maintainers could be included on that page, as an option.
 
So here are my questions regarding PyGMT specifically:

1. Do people think it would be helpful to publicly list the PyGMT maintainers? 
2. Are maintainers comfortable with being included on some sort of team page? (this could be discussed on slack)
3. If so, should this be done on the same page as the GMT teams or a separate page? If it's a separate page, should it be hosted on www.generic-mapping-tools.org or elsewhere?

*Originally posted in https://github.com/GenericMappingTools/pygmt/issues/1113#issuecomment-805343339*.

**Comment by willschlitzer** [comment]
>     1. Do people think it would be helpful to publicly list the PyGMT maintainers?

Yes, I think it's a good way to demonstrate to people coming to the project that they can contribute, as it puts a face on the people they are interacting with. I think seeing that we're not all computer scientists encourages people who may doubt they have the skills and experience to work on the project.

>     2. Are maintainers comfortable with being included on some sort of team
>     page? (this could be discussed on slack)

For me personally, yes.

>     3. If so, should this be done on the same page as the GMT teams or a separate page? 
>     If it's a separate page, should it be hosted on www.generic-mapping-tools.org or elsewhere?

Why wouldn't this be on the PyGMT page? I think that would make more sense to someone coming to the project, as our goal is to improve our wrapper and documentation until users need only be familiar with PyGMT and not have to refer back to GMT documentation to learn the correct syntax.

**Comment by meghanrjones** [comment]
> Why wouldn't this be on the PyGMT page? I think that would make more sense to someone coming to the project, as our goal is to improve our wrapper and documentation until users need only be familiar with PyGMT and not have to refer back to GMT documentation to learn the correct syntax.

I had been looking at organizations like project Jupyter and Numpy when considering options for the placement of the teams page. For those projects, information about teams are on the organization webpages (https://jupyter.org/about and https://numpy.org/gallery/team.html) rather than inside the reference documentation for the packages (https://jupyter.readthedocs.io/en/latest/ and https://numpy.org/doc/stable/). I viewed https://www.generic-mapping-tools.org/ as the most analogous place for GMT (and possibly PyGMT/GMT-MEX/GMT.jl) teams, rather than inside the reference documentation (i.e., https://docs.generic-mapping-tools.org/latest/ and https://www.pygmt.org/latest/).

**Comment by seisman** [comment]
Please note that the link https://www.generic-mapping-tools.org/team is already taken and is redirected to the https://github.com/GenericMappingTools/gmt/blob/master/AUTHORS.md file.

**Comment by seisman** [comment]
I'm reopening the 3-year-old issue to post some thoughts on the ["Team Gallery"](https://www.pygmt.org/dev/team.html) page:

1. Rename the page title from "Team Gallery" to "PyGMT Team" or "Team"
2. Currently, everyone is listed under the "Distinguished Contributors" section. Maybe we should have sections like "Founders", "Current Active Maintainers" and "Distinguished Contributors"?
3. Maintainers may be inactive due to lacking of time or interest and should be removed. Currently, we only mention that "New Distinguished Contributors are selected twice per year by those listed below." What's the policy for removing a maintainer? Maybe move from "Maintainers" to "Contributors" if someone is inactive for one year? Of course, inactive maintainers are welcome back at any time.
4. We should add a reminder in the Release checklist issue template, so that we don't forget to  update the team gallery.

Ping @GenericMappingTools/pygmt-maintainers for thoughts.

**Comment by yvonnefroehlich** [comment]
> I'm reopening the 3-year-old issue to post some thoughts on the ["Team Gallery"](https://www.pygmt.org/dev/team.html) page:
> 
> 1. Rename the page title from "Team Gallery" to "PyGMT Team" or "Team"

"PyGMT Team" as title sounds good to me.

> 2. Currently, everyone is listed under the "Distinguished Contributors" section. Maybe we should have sections like "Founders", "Current Active Maintainers" and "Distinguished Contributors"?

I am fine with having different sections related to the different roles. What's about "Core Developer"? However, we should not have more then four / five sections, as there are currently ten people listed on the Team Gallery page.

> 3. Maintainers may be inactive due to lacking of time or interest and should be removed. Currently, we only mention that "New Distinguished Contributors are selected twice per year by those listed below." What's the policy for removing a maintainer? Maybe move from "Maintainers" to "Contributors" if someone is inactive for one year? Of course, inactive maintainers are welcome back at any time.

pandas separates between "active maintainers" and "inactive maintainers".
One year sounds fair to me. How do we want to define inactive?

> 4. We should add a reminder in the Release checklist issue template, so that we don't forget to  update the team gallery.

This makes sense :grimacing:.

**Comment by seisman** [comment]
> > 2. Currently, everyone is listed under the "Distinguished Contributors" section. Maybe we should have sections like "Founders", "Current Active Maintainers" and "Distinguished Contributors"?
> 
> I am fine with having different sections related to the different roles. What's about "Core Developer"? However, we should not have more then four / five sections, as there are currently ten people listed on the Team Gallery page.

Yes, I agree. I also prefer to not list one person in multiple sections.

> > 3. Maintainers may be inactive due to lacking of time or interest and should be removed. Currently, we only mention that "New Distinguished Contributors are selected twice per year by those listed below." What's the policy for removing a maintainer? Maybe move from "Maintainers" to "Contributors" if someone is inactive for one year? Of course, inactive maintainers are welcome back at any time.
> 
> pandas separates between "active maintainers" and "inactive maintainers". One year sounds fair to me. How do we want to define inactive?

Maintainers are contributors with more permissions and more responsibilities (tasks listed in https://www.pygmt.org/dev/maintenance.html). A maintainer should be marked as "inactive" if he/she no longer manage issues, review PRs, manage releases and participate in discussions.

**Comment by yvonnefroehlich** [comment]
Just tried two variants:

| **three sections** | **five sections** |
| --- | --- |
| ![teampage_threesections](https://github.com/GenericMappingTools/pygmt/assets/94163266/4829670c-f05c-48c8-9927-43eb163622df) | ![teampage_fivesections](https://github.com/GenericMappingTools/pygmt/assets/94163266/588f438d-df9b-4fe3-9797-41cbe3d1ef00) |

**Comment by seisman** [comment]
I prefer the left one with three sections. I think we just need to add a few sentences explaining that distinguished contributors include current or past contributors and past maintainers.

**Comment by yvonnefroehlich** [comment]
I submitted PR #3240 for the three-sections variant.
