### ISSUE TITLE
Reduce repeated code for managing the outgrid parameter

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/pygmt#1400]
**Description of the desired feature**

The block of code below is currently used seven times throughout PyGMT modules (probably more pending Will's PRs). Based on https://github.com/GenericMappingTools/gmt/issues/5563#issuecomment-889519995, it may need to be used up to 34 times if we continue adding functions 1:1 with GMT modules. I think it would be useful to add an `build_outgrid_args()` method (or something similar) that can be used throughout to build the argument string using either outgrid or tempfile.name. I expect this would be simplest to implement as a new method in the Session class, although it could be a function in utils.

https://github.com/GenericMappingTools/pygmt/blob/6a4b8715bf00cd42cae8d5405e35e08a4764e97c/pygmt/src/grdclip.py#L85-L88

Edit: The original post only mentioned managing the input arguments to call_module, but the same can be applied to the output for the current default behavior of returning a DataArray if outgrid is not set:

https://github.com/GenericMappingTools/pygmt/blob/6a4b8715bf00cd42cae8d5405e35e08a4764e97c/pygmt/src/grdclip.py#L91-L96

**Are you willing to help implement and maintain this feature?** Yes

**Comment by weiji14** [comment]
Yes, probably best to standardize this chunk if it's going to be used up to 34 times (!!!). Personally I wouldn't hide away the `if "G" not in kwargs.keys():` since there might be extra logic involved, e.g. at https://github.com/GenericMappingTools/pygmt/blob/b2808cf30e5e198515deabf17368ef0731bc84ab/pygmt/src/grdview.py#L127-L138

But certainly for the latter `if outgrid == tmpfile.name` block, we can have a function producing the correct output grid format. This can be called in a PyGMT module at the end using `return some_grid_function_name(result)`. Maybe start a new `pygmt/io.py` file to put all of PyGMT's Input/Output logic? Will tie in nicely with the table-output discussion happening at #1318, and could also be a good place longer-term to add in logic for the expanding variety of PyGMT input formats (xref #949).

**Comment by meghanrjones** [comment]
Cool, I can likely find time to work on this in late August if no one else posts that they would like to work on the issue before then.
