### ISSUE TITLE
Missing (required) parameters in grdlandmask

### ISSUE THREAD

**Issue by michaelgrund** [GenericMappingTools/pygmt#1421]
**Description of the desired feature**

I thought about generating a gallery example highlighting how to use `grdlandmask` (similar to #1396 for `grdclip`) based on the examples given under https://docs.generic-mapping-tools.org/6.2/grdlandmask.html. Please correct me if I'm wrong but for the case of plotting shoreslines already included in GMT at least the alias (and description) for parameter **-N** is missing, isn't it?

**Are you willing to help implement and maintain this feature?** Yes

**Comment by meghanrjones** [comment]
-N is not a required arguments since there is a default in GMT (setting values over water as 0 and values over land as 1). It is certainly useful since it allows completing tasks such as those in the examples. Feel free to propose an alias in a PR, since there is not already a PR open for adding more aliases to grdlandmask.
