### ISSUE TITLE
python setup.py gives deprecation warnings

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#1797]
In our CI workflow, we run commands like `python setup.py sdist --formats=zip` to build source or binary distributions. The command gives the following deprecation warnings:
```
SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
```
It seems `python setup.py` is no longer recommended to build distributions.

Reference: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary

**Comment by weiji14** [comment]
So reading into that blog post, it looks like we'll need to

### 1. Have `make package` do `python -m build`

Specifically, modify the line here:

https://github.com/GenericMappingTools/pygmt/blob/ba51f805bf23190bf5752785ac22a201b852cc6f/Makefile#L31-L32

And then, we'll need to add `build` as a dependency in the `publish-to-pypi.yml` workflow here:

https://github.com/GenericMappingTools/pygmt/blob/ba51f805bf23190bf5752785ac22a201b852cc6f/.github/workflows/publish-to-pypi.yml#L36-L37

Now the above is the minimum we can do. If we want to go for **hard** mode, it sounds like we can

### 2. Put everything in `pyproject.toml` somehow

I.e. remove `setup.py`, `setup.cfg` and all those crazy files in the top level directory. So a bit like #1055, but using 'native' pypa tools instead of poetry. But that will require a bit more reading into all those PEPs.

I'd recommend doing 1) for a PyGMT v0.6.1, and maybe save 2) for PyGMT v0.7.0
