### ISSUE TITLE
Suggestion for improvement of gallery examples regarding categorical colormaps

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/pygmt#1933]
In two gallery examples categorical data (without order) is displayed by using color-coding for the categories:
- [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html#sphx-glr-gallery-symbols-points-categorical-py)
- [3D Scatter plots](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html#sphx-glr-gallery-3d-plots-scatter3d-py)

The data (csv file) is loaded into a _pandas_ dataframe and the column of interest is converted to categorical data type. A discrete colormap in categorical format is set up via the `pygmt.makecpt()` function (`+c` through `color_model`). For plotting the symbols with the corresponding fill color the categorical number code is passed through the `color` parameter of the `pygmt.Figure.plot()` method.

I recommend to clarify that by default the labels for the colorbar must be given in **alphabetical** order. If one wants labels in non-alphabetical order, e. g. increasing or decreasing order for displaying categorical data with order, the categorical number code has to be adjusted by the user. For instance, to get '**p**oor, **f**air, **g**ood' instead of '**f**air, **g**ood, **p**oor' (dataframe 'df' with column 'quality'):
``df.quality = df.quality.cat.set_categories(['poor','fair','good'], ordered = True)``
The label order (comma-separated list) passed through `color_model` in the `pygmt.makecpt()` function has no effect on the plotting itself, but affects only the colorbar labels.

**Comment by seisman** [comment]
@yvonnefroehlich Nice catch!

I'm not familiar with pandas's category type, but looking at the two gallery examples, I think both examples should be improved.

I'll take [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html#sphx-glr-gallery-symbols-points-categorical-py) as an example. Here are the two important lines in the example:
```
df.species = df.species.astyp(dtype="category")
pygmt.makecpt(cmap="inferno", series=(0, 2, 1), color_model="+cAdelie,Chinstrap,Gentoo")
```
As pointed out by @yvonnefroehlich, the labels must be given in alphabetical order because when converting `df.species` to categorical dtype, the default order is alphabetical (e.g., 0-Adelie, 1-Chinstrap,2-Gentoo). So the examples have many limitations and are difficult to be re-used by users:

1. Users must know the labels `Adelie,Chinstrap,Gentoo`
2. The labels `Adelie,Chinstrap,Gentoo` must be given in alphabetical order in this case
3. Users must know the minimum and maximum values of categorical data (0 and 2 in this case).

So, instead of hard-coding the numbers and values in the `makecpt` call, we can rewrite it to:
```
df.species = df.species.astyp(dtype="category")

labels = list(df.species.cat.categories)
pygmt.makecpt(cmap="inferno", series=(df.species.cat.codes.min(), df.species.cat.codes.min(), 1), color_model="+c" + ",".join(labels))
```
