### ISSUE TITLE
Set the background color for the scale bar

### ISSUE THREAD

**Issue by De-Guo** [GenericMappingTools/pygmt#1951]
**Description of the desired feature**

Set a specific background color for the scale bar to make it more straightforward.

**Are you willing to help implement and maintain this feature?** Yes/No
No

**Comment by yvonnefroehlich** [comment]
Hopefully it is fine from the _PyGMT_ maintainer side, that I comment on this issue. Otherwise I am sorry, for doing so!

@De-Guo adding a box around the scale bar is already possible! :relaxed:
The `F` parameter of the method `pygmt.Figure.basemap()` is not wrapped in _PyGMT_ version <=0.6.1 (but in the developer version, see https://www.pygmt.org/dev/api/generated/pygmt.Figure.basemap.html). So, you have to use the single letter from _GMT_ instead of the long-parameter word `box`. You can set the fill color by appending `+g` and the transparency via `@` (in percentage, 0 equals opaque). Outline thickness and color of the box are set by `+p`. And `+r` generates a box with rounded edges.
For example, let's create a box with rounded edges, a gray fill color with a transparency of 30 % and a black outline with a thickness of 1.0p.
```
import pygmt as gmt 

# create figure object
fig = gmt.Figure()

fig.basemap(
    region = '0/10/0/10',
    projection = 'M10c',
    frame = 'agf',
    map_scale = 'JMC+JMC+w500+c5/5+f+lkm', # fancy
    F = '+ggray@30+p1.0p,black+r',
    )

fig.show()
# fig.savefig(fname='scalebar_with_fillcolor.png',dpi=360,)
```
![scalebar_with_fillcolor](https://user-images.githubusercontent.com/94163266/173321546-ff48ce61-0525-47bc-99b6-ef699e3ef15b.png)

**Comment by De-Guo** [comment]
> 

Thanks, it can solve my problem. I hope `box` become available soon.

**Comment by seisman** [comment]
@yvonnefroehlich Thanks for your quick and nice answer. As `box` is already aliased in the dev version, I'm closing the issue.
