### ISSUE TITLE
Wrapper for makecpt

### ISSUE THREAD

**Issue by mlmarius** [GenericMappingTools/pygmt#214]
## Python 3.6, GMT 6

* Operating system:
* Python installation: system (inside docker container):
* Version of GMT/Python: 6, 3.6
* How you installed GMT/Python: Docker image

Apparently the examples shown here: https://www.gmtpython.xyz/latest/design.html#the-gmt-python-api are not working. How do i generate a colorbar and a legend for my plot ? Is there a way to work directly with the gmt modules ?

**Comment by leouieda** [comment]
Hi @mlmarius, the "Design" page was more of a roadmap for us than a tutorial. Sadly, we let it get out of date. We're working on updating the documentation (#201).

We haven't implemented makecpt yet because there are still some issues with how we're communicating with the C API. Right now, there is no way to call GMT modules directly.

We'll update this issue when we have makecpt implemented, so you'll get a notification.
