### ISSUE TITLE
How to reduce width of the errorbar and the errorbar cap  in asymmetrical errorbar

### ISSUE THREAD

**Issue by seismoprocess** [GenericMappingTools/pygmt#2182]
### Description of the problem

Dear experts,
I am able to plot the symmetrical errorbar on the map by using the below code. But i want to plot the asymmetrical errorbar on the map and i need to change the width of the errorbar and errorbar cap size. What should i add in the below code can you please suggest.

### Minimal Complete Verifiable Example

```python
import pandas as pd
import pygmt

df = pd.DataFrame(
data={
“x”: [181.89470, 181.89470, 195.63454, 195.63454, 195.63454],
“y”: [-4.0, -4.0, -4.0, -4.0, -4.0],
“x-error”: [0.5, 0.0, 0.0, 0.5, 0.0],
“y-error”: [1.0, 1.0, 1.5, 1.5, 1.5],
}
)

fig = pygmt.Figure()
fig.plot(data=df.to_numpy(), region=[180., 198., -6., -2.], error_bar=True, frame=True)
fig.show()
```

### Full error message

```python-traceback
pygmt.exceptions.GMTInvalidInput: Parameters
```

### System information

```bash
Ubuntu 22.04 LTS
pygmt new version
```

**Comment by yvonnefroehlich** [comment]
I think this issue is a dublicate of this GMT forum post https://forum.generic-mapping-tools.org/t/how-to-reduce-width-of-the-errorbar-and-the-errorbar-cap/3409.

All three aspects can be accomplished using the `error_bar` parameter (see [plot — GMT 6.4.0 documentation (generic-mapping-tools.org)](https://docs.generic-mapping-tools.org/6.4/plot.html#e)):
- `+a` for asymmetric error bars
- `+w` to adjust the cap size
- `+p` to adjust the width and color of the bar

Please find below an example as orientation (PyGMT v0.7.0 and GMT 6.4.0):
```python
import pandas as pd
import pygmt

df = pd.DataFrame(
    data={
    "x": [5],
    "y": [5],
    "x-error-low": [1],
    "x-error-upp": [2],
    "y-error-low": [2.5],
    "y-error-upp": [3],
    }
)

fig = pygmt.Figure()

fig.plot(data=df.to_numpy(),
         region=[0, 10, 0, 10],
         projection="X10c",
         # +a asymmetric errorbars
         # +w size of cap
         # +p with, color of bar
         error_bar="+a+w10p+p2p,red",
         style="c0.25c",  # circle
         pen="1p,black",  # outline width and color
         color="green",  # fill color
         frame="a1fg1",
)

fig.show()
```

Output figure:
![errorbars](https://user-images.githubusercontent.com/94163266/200137091-6cecc763-a398-469b-b447-3948d07b730f.png)

**Comment by yvonnefroehlich** [comment]
The issue aises probably from an (copy-and-past) error in the PyGMT documentation. The syntax for `- L` or `close` was added to `error_bar`:

- PyGMT: `error_bar (bool or str) – [+b|d|D][+xl|r|x0][+yl|r|y0][+ppen]` (see https://www.pygmt.org/dev/api/generated/pygmt.Figure.plot.html#pygmt.Figure.plot)
- GMT: `-E[x|y|X|Y][+a|A][+cl|f][+n][+wcap][+ppen]` (see https://docs.generic-mapping-tools.org/dev/plot.html#e)
