### ISSUE TITLE
NEP29: Don't drop Python 3.8 support until Google Colab upgrades to Python 3.9 or above?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2300]
As per the [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) policy, we will drop Python 3.8 support on Apr 14, 2023.

Google Colab is slowly upgrading its Python version. Recently, they finally upgraded to Python 3.8 (https://github.com/googlecolab/colabtools/issues/3246) after a three-year delay. The upgrade to Python 3.9 or newer is still ongoing (https://github.com/googlecolab/colabtools/issues/2165). If we drop Python 3.8 support in the next PyGMT version, then Google Colab users won't be able to use the latest PyGMT versions.

Considering that supporting old Python versions is not a big burden for us (we're not using features in new Python versions), I'm unsure if we can still support Python 3.8 until Google Colab upgrades to Python 3.9 or newer.

**Comment by weiji14** [comment]
Let's wait and see, Google is experiencing some mass layoffs now, so support might be lacking :slightly_smiling_face:

Personally, we could do:
- Release PyGMT v0.9.0 before Apr 14 2023, and that version will support Python 3.8
- Release PyGMT v0.10.0 (sometime mid 2023?), we could decide to keep Python 3.8 if Google Colab doesn't support Python 3.9 yet
- Release PyGMT v0.11.0, I think we should drop Python 3.8 regardless of whether Google Colab has upgraded to Python 3.9, otherwise we'll be falling behind on NEP29, and we don't want too big a range of supported Python versions in our CI, especially if we're starting to support Python 3.12 ([scheduled for 2023-10-02](https://peps.python.org/pep-0693/)).

**Comment by maxrjones** [comment]
Xarray just dropped 3.8 and is now relying on 3.9+ features, so think we'll need to drop 3.8 for the next release. I'm actually a bit confused by xarray's rolling policy relative to NEP 29 and will ask for clarification.

**Comment by weiji14** [comment]
According to https://docs.xarray.dev/en/v2023.02.0/getting-started-guide/installing.html#minimum-dependency-versions, `xarray` supports Python versions that are within a 24 month range, which is more aggressive than NEP29's 42 month range. The strange thing is that `xarray` references NEP29, so it doesn't make a lot of sense.

I still think that we should keep supporting Python 3.8 for PyGMT v0.9.0. That means users would be able to use `xarray` versions up to [v2023.01.0](https://github.com/pydata/xarray/releases/tag/v2023.01.0). Should we be starting to think about a release by the end of March?

**Comment by seisman** [comment]
> I still think that we should keep supporting Python 3.8 for PyGMT v0.9.0.

Yes to me.

> Should we be starting to think about a release by the end of March?

Yes.

**Comment by maxrjones** [comment]
> According to https://docs.xarray.dev/en/v2023.02.0/getting-started-guide/installing.html#minimum-dependency-versions, xarray supports Python versions that are within a 24 month range, which is more aggressive than NEP29's 42 month range. The strange thing is that xarray references NEP29, so it doesn't make a lot of sense.

I was confused about this as well - started https://github.com/pydata/xarray/discussions/7482 for that reason.

>  I still think that we should keep supporting Python 3.8 for PyGMT v0.9.0.

Could we use [conditional dependencies](https://peps.python.org/pep-0631/) to specify the xarray requirements for Python 3.8?

**Comment by seisman** [comment]
The good news is that it's very likely that Google Colab already upgraded its Python version to 3.9 (xref: https://github.com/googlecolab/colabtools/issues/3450).

**Comment by maxrjones** [comment]
> The good news is that it's very likely that Google Colab already upgraded its Python version to 3.9 (xref: https://github.com/googlecolab/colabtools/issues/3450).

I don't have pro to check if the fallback runtime still has 3.8 available, but the default runtime was 3.9 on a quick test.

**Comment by weiji14** [comment]
> The good news is that it's very likely that Google Colab already upgraded its Python version to 3.9 (xref: https://github.com/googlecolab/colabtools/issues/3450).

Oo, that changes things. In that case, I'm indifferent with keeping Python 3.8 or dropping it. What does the team think?

**Comment by seisman** [comment]
I think it really depends on when we do the v0.9.0 release. If we do the release before April, then we should still support Python 3.8 following NEP29.

**Comment by weiji14** [comment]
> I think it really depends on when we do the v0.9.0 release. If we do the release before April, then we should still support Python 3.8 following NEP29.

Ok, so PyGMT v0.9.0 was released and that still supports Python 3.8. Can we decide on whether to drop Python 3.8 in PyGMT v0.10.0 so that it can be mentioned in the PyGMT v0.9.0 forum post, xref https://github.com/GenericMappingTools/pygmt/issues/2424#issuecomment-1496719163? :+1: for dropping Python 3.8.
