### ISSUE TITLE
Support upper-case file extensions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#2683]
### Description of the desired feature

Currently, PyGMT only allows lower-case file extensions like pdf and png, but doesn't support upper-case extensions like PDF or PNG. The Windows OS is case insensitive, so both lower-case and upper-case file extensions should be allowed.

```python
import pygmt
fig = pygmt.Figure()
fig.basemap(region=[0, 10, 0, 10], frame=True)
fig.savefig("map.PNG")
---------------------------------------------------------------------------
GMTInvalidInput                           Traceback (most recent call last)
Cell In[4], line 1
----> 1 fig.savefig("map.PNG")

File pygmt/pygmt/figure.py:315, in Figure.savefig(self, fname, transparent, crop, anti_alias, show, **kwargs)
    310     if ext == "ps":
    311         raise GMTInvalidInput(
    312             "Extension '.ps' is not supported. "
    313             "Please use '.eps' or '.pdf' instead."
    314         )
--> 315     raise GMTInvalidInput(f"Unknown extension '.{ext}'.")
    316 fmt = fmts[ext]
    317 if transparent:

GMTInvalidInput: Unknown extension '.PNG'.
```

### Are you willing to help implement and maintain this feature?

Maybe

**Comment by MichaelCni** [comment]
Hy there i can see your post and i must say

Normalization:

When dealing with file extensions provided by users or retrieved from external sources, normalize them to lowercase before processing. This ensures consistency.
Validation and Handling:

Ensure that your application correctly validates and handles files with uppercase or lowercase extensions. This includes loading, displaying, and processing the files.
File Type Mapping:

Maintain a mapping of file extensions to corresponding file types or actions in your application. Make sure this mapping is case-insensitive so that both uppercase and lowercase extensions trigger the correct behavior.
User Input Handling:

If your application allows users to input file extensions (e.g., in filters or preferences), make sure that it gracefully handles both uppercase and lowercase inputs.

Thanks and regards
MichaelCni
