### ISSUE TITLE
Figure.grdcontour: improve the documentation of the pen parameter

### ISSUE THREAD

**Issue by HouseJaay** [GenericMappingTools/pygmt#2704]
Please describe what could be improved about this page or the typo/mistake that you found:
"pen (str) – Set pen attributes for lines or the outline of symbols."
should be:
"pen (str, list) – Set pen attributes for lines or the outline of symbols."
Because we can set pen attributes for contour lines with and without annotations separately.
Example: pen=['a0.75p,white', 'c0.25p,white'].

**Comment by yvonnefroehlich** [comment]
Thanks @HouseJaay for pointing out this limitation of the docstrings 🙂!

Actually this is not only relevant for [`Figure.grdcontour`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.grdcontour.html), but also for [`Figure.contour`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.contour.html).

For these two methods, I feel we should not only update the allowed input types for the `pen` parameter but also improve the docstring following the upstream GMT documentation instead of using the general formulation defined in the[ `decorators.py`](https://github.com/GenericMappingTools/pygmt/blob/main/pygmt/helpers/decorators.py#L90) file:

- `grdcontour`: https://docs.generic-mapping-tools.org/6.4/grdcontour.html#w
   `Figure.grdcontour`: https://github.com/GenericMappingTools/pygmt/blob/f21119b843eb2fa9369c25af59d485a76ed2e07b/pygmt/src/grdcontour.py#L83
- `contour`: https://docs.generic-mapping-tools.org/6.4/contour.html#w
   `Figure.contour`: 
https://github.com/GenericMappingTools/pygmt/blob/f21119b843eb2fa9369c25af59d485a76ed2e07b/pygmt/src/contour.py#L96

If you'd like to work on these updates, feel free to submit a pull request. For details on how contributing to PyGMT works, you may want to take a look at our [Contributors Guide](https://www.pygmt.org/dev/contributing.html). Please ask any questions you have.

**Comment by yvonnefroehlich** [comment]
What is the status on this issue? Would be fine if I submit a PR for improving the docstring for the `pen` parameter for both `Figure.grdcontour` and `Figure.contour`?

**Comment by seisman** [comment]
Yes, please improve the docstrings following the GMT docs.

**Comment by yvonnefroehlich** [comment]
> Yes, please improve the docstrings following the GMT docs.

Submitted PR #3210 for this.
