### ISSUE TITLE
Use "PyData Ecosystem" or "Scientific Python Ecosystem"?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3442]
In the [project goals](https://github.com/GenericMappingTools/pygmt#project-goals), we mention that:

> Integration with the [PyData ecosystem](https://pydata.org/): numpy.ndarray or pandas.DataFrame for data tables, xarray.DataArray for grids, and geopandas.GeoDataFrame for geographical data.

After looking at the link https://pydata.org/, users (and even myself) may be still confused with the definition and scope of "PyData Ecosystem". The best explanation of "PyData Ecosystem" may be this post: https://stackoverflow.com/questions/18168400/the-pydata-ecosystem.

In addition to "PyData Ecosystem", a similar term is "Scientific Python Ecosystem". This term is used on the NumPy Nature paper (https://www.nature.com/articles/s41586-020-2649-2#Sec3 and the figure 2 https://www.nature.com/articles/s41586-020-2649-2/figures/2) and across the [scientific Python site](https://scientific-python.org/). The term is also well defined at https://tools.scientific-python.org/about/:

> The Scientific Python ecosystem is a loose federation of community developed and owned Python projects widely used in scientific research, technical computing, and data science.

I think we should use "Scientific Python Ecosystem" instead of "PyData Ecosystem".

**Comment by yvonnefroehlich** [comment]
It’s nice that you bring up this discussion.
Actually, I was also wondering about the difference between the "PyData Ecosystem" and "Scientific Python Ecosystem" but I did not look at this in more detail. Looking at your links am I also a bit usure about the exact definition of "PyData Ecosystem" (is this a community, a conference, or a list of Python libraries / packages?).

The SPEC 0 rules we are following are related to the “Scientific Python ecosystem” (https://www.pygmt.org/dev/minversions.html) and in the [AGU abstract](https://hackmd.io/9Q5jolmqQc6bHEnkc3mNwA) we wrote “Scientific Python ecosystem”:

> PyGMT integrates smoothly within the Scientific Python ecosystem

Despite we currently write in the [README](https://github.com/GenericMappingTools/pygmt?tab=readme-ov-file#project-goals):

> Integration with the PyData ecosystem: numpy.ndarray or pandas.DataFrame for data tables, xarray.DataArray for grids, and geopandas.GeoDataFrame for geographical data

**Comment by yvonnefroehlich** [comment]
So, after looking at Fig. 2 of the mentioned NumPy Nature publication (https://www.nature.com/articles/s41586-020-2649-2#Fig2) in more detail I feel using consistently "Scientific Python ecosystem" makes sense. In this figure they list different libraries and projects, which cover the data types we mention in the README:
> Integration with the [PyData ecosystem](https://pydata.org/): numpy.ndarray or pandas.DataFrame for data tables, xarray.DataArray for grids, and geopandas.GeoDataFrame for geographical data.

**Comment by weiji14** [comment]
That sentence used to read "Integration with the SciPy stack" :laughing: I suggested at https://github.com/GenericMappingTools/pygmt/pull/605#discussion_r487601925 to change it to "PyData Ecosystem" based on this [stackoverflow answer](https://stackoverflow.com/questions/18168400/the-pydata-ecosystem), but the intention was more around PyData "data structures" (like numpy arrays, pandas dataframes, xarray dataarrays, etc).

As of 2024, I think 'PyData' has expanded quite a bit since NumFOCUS is sponsoring many projects now (see https://numfocus.org/sponsored-projects/?_sft_project_category=python-interface), so the term is a bit more vague. Changing it to Scientific Python Ecosystem sounds good since we have a policy around [SPEC 0](https://scientific-python.org/specs/spec-0000) and that page has a concrete list of packages/dependencies we integrate with.

**Comment by seisman** [comment]
We will go with the "Scientific Python Ecosystem".
