### ISSUE TITLE
Add the 2024 AGU PyGMT talk and workshop to the documentation 

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#3683]
After the AGU meeting, we should

- [x] add the [PyGMT talk](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1578856) to the [overview](https://www.pygmt.org/dev/overview.html) page: #3685 
- [x] add the [GMT/PyGMT workshop](https://www.generic-mapping-tools.org/agu24workshop/intro.html) to the [External Resources](https://www.pygmt.org/dev/external_resources.html) page #3689

**Comment by yvonnefroehlich** [comment]
BTW there was an iposter presentation on PyGMT at AGU 2021:
- https://github.com/GenericMappingTools/pygmt/issues/1395
- https://hackmd.io/i4XjR4PxSn6ZTrtkAcA-5A

and it looks like this conference contribution has not been added to the overview list yet (https://www.pygmt.org/dev/overview.html#presentations).

**Comment by yvonnefroehlich** [comment]
I opened PR #3685 for adding our PyGMT talk, also started to include adding the preworkshop in this PR; please indicate if we want to separat PRs.

**Comment by seisman** [comment]
Separate PRs are better

**Comment by seisman** [comment]
> BTW there was an iposter presentation on PyGMT at AGU 2021:
> 
> * [PyGMT abstract submission for AGU 2021 Fall Meeting #1395](https://github.com/GenericMappingTools/pygmt/issues/1395)
> * https://hackmd.io/i4XjR4PxSn6ZTrtkAcA-5A
> 
> and it looks like this conference contribution has not been added to the overview list yet (https://www.pygmt.org/dev/overview.html#presentations).

Yes, we can add it if the poster can be uploaded somewhere.

**Comment by yvonnefroehlich** [comment]
> Yes, we can add it if the poster can be uploaded somewhere.

Hm. I am afraid this is not directly possible as these posters are prepared in an online plattform via the AGU portal. Also the majority of these kind of posters are not static but include slideshows, gifs, videos, etc. The materials are available some time after the conference for registered participantes, but as far as I know there is no good way to export these posters. Maybe this was the reason why this conferece contribution was not added.

---
I accidently clicked "Edit" instead of "Quote reply". I have redone the changes in your comment above @seisman.
