### ISSUE TITLE
Fix ZEIT/now to Vercel

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#447]
**Description of the problem**

We use the ZEIT/now service for continuously building the documentation for each commit. Recently, ZEIT changed their name to Vercel (https://vercel.com/blog/zeit-is-now-vercel). The configuration file `now.json` also changed to `vercel.json`. We may need to update it accordingly. 

I may be wrong here, as I didn't check the documentation carefully.

**Comment by weiji14** [comment]
Yes, I did notice it a while back, but everything still seems to work using the [Github Now App](https://github.com/apps/now). There doesn't seem to be a Vercel app (yet?), but there *is* a Github Action at https://github.com/amondnet/vercel-action that does the same thing I guess.

So we probably don't need to change anything for now. But it would be nice to move to the Github Action at some point as it *should* allow us to trigger the builds via a command (like `/now build`?)  instead of every commit.

**Comment by seisman** [comment]
It seems the only thing we need to do is renaming "now.json" to "vercel.json" (although now.json is still supported).

As for the vercel-action, I don't see any benefits to switch to the action. As per the documentation (https://github.com/amondnet/vercel-action#disable-vercel-for-github), we still need the "vercel.json" file to disable the vercel-github integration. Using the vercel-action means we need three files "vercel.json", "package.json" and the workflow file.
