### ISSUE TITLE
adding set to figure

### ISSUE THREAD

**Issue by yohaimagen** [GenericMappingTools/pygmt#540]
Hi all and thank you for developing a GMT interface for python.

**Description of the desired feature**
I think that adding the set function will help significantly to improve the versatility and features of the outputted figures.

to my opinion, it should be something like(not sure where maybe in BasePlotting?)

def set(self,  **kwargs):

where kwargs is a dictionary of parameters:parameters_value

Examples

Example 1 
Change the geographic coordination format from minutes seconds to decimal.

gmt set FORMAT_GEO_MAP=ddd.x
gmt psbasemap -JM10 -R-119/-117/34/36 -BWSne -Bxa0.5f0.1 -Bya0.5f0.1 > temp

![temp](https://user-images.githubusercontent.com/12828255/88031674-93bc6200-cb45-11ea-98fd-0162dc23d073.png)

Example 2
Change the annotation font

gmt set FONT_ANNOT_PRIMARY=15p,Helvetica,red 
gmt psbasemap -JM10 -R-119/-117/34/36 -BWSne -Bxa0.5f0.1 -Bya0.5f0.1 > temp.ps

![temp](https://user-images.githubusercontent.com/12828255/88032475-abe0b100-cb46-11ea-8081-52623ba54dac.png)

there are a lot more options at [GMT doc](http://gmt.soest.hawaii.edu/doc/latest/gmt.conf.html)

**Are you willing to help implement and maintain this feature?** Yes/No
Yes, I am willing to try and implement this feature. I will. need some guidance on your GMT c interface and the direction on how to implement it.

**Comment by weiji14** [comment]
Hi @yohaimagen, we actually have this already! It's called `pygmt.config` (see https://www.pygmt.org/v0.1.2/api/generated/pygmt.config.html), we decided not to use the name `set` because it's a reserved python function.

@hemmelig is working on adding a tutorial example for this at #482 that should make it more discoverable. In the meantime, have a look at https://pygmt-79i86f8si.vercel.app/tutorials/gmt-config.html to see how you can use this.

**Comment by yohaimagen** [comment]
Great, thanks.

**Comment by weiji14** [comment]
No problem, feel free to let us know if you'd like any other new features :smile:
