### ISSUE TITLE
Migrate Travis CI jobs to GitHub Actions

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/pygmt#566]
**Description of the desired feature**

We recently migrated all the CI testings and style checks from Azure Pipelines to GitHub Actions. Currently, we're using both GitHub Actions and Travis CI.

The Travis CI is doing following jobs:

- ~~Test PyGMT with Python 3.6-3.8 on Linux~~
- [ ] Deploy documentation to gh-pages branch for master branch and tags
- [x] Publish PyGMT to PyPi for tags (#679)

The first one is already covered in the GitHub Actions, so it's OK to just remove them from Travis CI.

The 2nd and the 3rd one should be migrated to GitHub Actions.

**Are you willing to help implement and maintain this feature?** Yes, but contributions are welcome.

**Comment by weiji14** [comment]
No strong objections to this, we should do all three in separate PRs. Only concern would be that this makes up totally dependent on Github, which might be problematic if GIthub servers go down (but that's a bigger issue in itself).

> The first one is already covered in the GitHub Actions, so it's OK to just remove them from Travis CI.

Yep. Or we could keep one single test around. Maybe a test for a [nightly Python build](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions) for the upcoming Python 3.9?

> The 2nd and the 3rd one should be migrated to GitHub Actions.

On the 2nd one, see https://github.com/GenericMappingTools/website/pull/65 as an example on documentation build/deploy.

For the 3rd one (Publish to PyPI), we could use https://github.com/marketplace/actions/pypi-publish, and maybe test it on https://test.pypi.org (instead of the main pypi.org website) first to be sure we don't break anything.

**Comment by seisman** [comment]
> > The first one is already covered in the GitHub Actions, so it's OK to just remove them from Travis CI.
> 
> Yep. Or we could keep one single test around. Maybe a test for a [nightly Python build](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions) for the upcoming Python 3.9?

We rely on packages from conda-forge. If conda-forge doesn't provide numpy, pandas and xarray packages for Python 3.9, I don't think we can get the testings running.

 
> > The 2nd and the 3rd one should be migrated to GitHub Actions.
> 
> On the 2nd one, see [GenericMappingTools/website#65](https://github.com/GenericMappingTools/website/pull/65) as an example on documentation build/deploy.

We still need the https://github.com/fatiando/continuous-integration/blob/master/travis/deploy-gh-pages.sh script, because documentation of different versions are stored in separated directories.
 
> For the 3rd one (Publish to PyPI), we could use https://github.com/marketplace/actions/pypi-publish, and maybe test it on https://test.pypi.org (instead of the main pypi.org website) first to be sure we don't break anything.

To make it work, we may need a PyPI token.

**Comment by seisman** [comment]
> We still need the https://github.com/fatiando/continuous-integration/blob/master/travis/deploy-gh-pages.sh script, because documentation of different versions are stored in separated directories.

We may not need the script, as the [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) action supports ["deploying to a subdirectory"](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-subdirectory-destination_dir).

**Comment by seisman** [comment]
FYI, I've added a pypi token in secret `pypi_password`, which can be used in the https://github.com/marketplace/actions/pypi-publish action.
