### ISSUE TITLE
OSError when using pygmt.grdimage with shading=True param

### ISSUE THREAD

**Issue by liwentao-319** [GenericMappingTools/pygmt#638]
**Description of the problem**
Hi!

Yesterday I installed gmt6 and pygmt with conda on win10 system. It is very easy to use. I have ploted some figures with pygmt module. It is all fine until I add shading=True to pygmt.grdimage. Besides I can't pass the grid (xarray.DataArray) to call_module("grdgradient") using virtual_from_grid. The error is something about 
"access violation reading",  and  I need some help to sovle this !! 

**code1 -> error1**
![image](https://user-images.githubusercontent.com/72292548/94985041-4b79e100-0585-11eb-80ee-a0a671dd34e8.png)

![image](https://user-images.githubusercontent.com/72292548/94985047-651b2880-0585-11eb-838c-eab693382e79.png)

**code2->error2**
![image](https://user-images.githubusercontent.com/72292548/94985114-3782af00-0586-11eb-87f7-23a1b6a98b7e.png)

**System information**

![image](https://user-images.githubusercontent.com/72292548/94985132-5b45f500-0586-11eb-86b5-8b8e7eed4152.png)

**Comment by weiji14** [comment]
> I have ploted some figures with pygmt module. It is all fine until I add shading=True to pygmt.grdimage.

你好 @liwentao-319, thanks for raising the issue and the kind words! What you are experiencing with `grdimage` shading *may* be a similar issue to #364. We tried to fix it in #581 but it appears to be an upstream issue with GMT 6.1.1, so it might take a while to fix (November 2020 probably), but it is definitely a priority for the next PyGMT v0.2.1 or v0.3.0 release.

In the meantime, if you really want `grdimage` with shading, either use pure GMT to do so, or try downgrading to GMT 6.1.0 and see if it works (though this comes with other issues).

> Besides I can't pass the grid (xarray.DataArray) to call_module("grdgradient") using virtual_from_grid. The error is something about "access violation reading", and I need some help to sovle this !!

I've not seen this error before, might be a Windows thing, and I'll only have access to a Windows machine to check this. You could try using `GMTTempFile(suffix=".nc")` to see if it helps, but do note that what you're using is a 'hack' and not something we support officially. If you have some time, you're welcome to submit a Pull Request to wrap `grdgradient`, I'm sure the community will greatly appreciate it :smile:

Also, in the future, please post your error messages as text instead of as a screenshot, this will help users in the future to more easily search for the same issue!

**Comment by liwentao-319** [comment]
OK,  I will try it and post my codes and error messages as text next time. And thanks for your reply!

**Comment by seisman** [comment]
@liwentao-319 As mentioned by @weiji14, the issue may be caused by an upstream GMT bug. In the upstream PR https://github.com/GenericMappingTools/gmt/pull/4328, a related bug was fixed, and the PR may also fix the issue you're having. It would be better if you can try your scripts with the GMT development version.

As an Anaconda user, you can run `conda install -c conda-forge/label/dev gmt` to install the GMT development version. Please let us know if it solves your problems. Thanks.

**Comment by liwentao-319** [comment]
@seisman The command you advised works well. Thank you very much!!
